rootDir: /Users/brunoalassia/Sauce/sauce-cypress-runner
targetDir: /Users/brunoalassia/Sauce/sauce-cypress-runner
reportsDir: /Users/brunoalassia/Sauce/sauce-cypress-runner/cypress/reports
execCommand:
  - npm
  - test
