apiVersion: v1alpha
metadata:
  name: Feature XYZ
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
  - cypress/integration/example.test.js
suites:
  - name: "saucy test"
    match: ".*.(spec|test).js$"
image:
  base: saucelabs/stt-cypress-mocha-node
  version: ##VERSION##
sauce:
  region: us-west-1
