name: Monthly Dependency Update

on:
  schedule:
    - cron: '0 9 1 * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    name: Monthly dependency update
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Upgrade dependencies with ncu
        run: |
          ncu -u
          npm install

      - name: Check for changes
        id: git-check
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: monthly dependency update"
          title: "chore: Monthly npm dependency upgrade"
          body: |
            This PR was automatically generated to update dependencies to the latest version.
          branch: chore/monthly-ncu-upgrade
          delete-branch: true