name: Validate Docker Release

on:
  push:
    tags:
      - 'b*.*.*'
jobs:  
  release-github:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo ::set-output name=version::${VERSION}
          npm version from-git
  release-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1      
      -
        name: Prepare
        id: prep
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo ::set-output name=version::${VERSION}
          npm version from-git
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ./Dockerfile
          tags: |
            saucelabs/stt-cypress-mocha-node:latest
            saucelabs/stt-cypress-mocha-node:${{ steps.prep.outputs.version }}
  release-windows-bundle:
    runs-on: windows-latest
    needs: release-github
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm version from-git
