# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-consistency:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Check consistency
        run: |
          DOCKERIMAGE_VERSION=$(grep "ENV CYPRESS_VERSION=" Dockerfile | cut -d '=' -f 2)
          CYPRESS_VERSION=$(< package-lock.json jq -r '.dependencies["cypress"].version')

          if [ "${DOCKERIMAGE_VERSION}" != "${CYPRESS_VERSION}" ];then
            echo "Cypress version in package-lock.json and Dockerfile differs."
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run unit-test
    - run: npm run lint
